# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Customer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, firstname: str=None, lastname: str=None, address: str=None, phone: str=None, begin_date: date=None):  # noqa: E501
        """Customer - a model defined in Swagger

        :param id: The id of this Customer.  # noqa: E501
        :type id: int
        :param firstname: The firstname of this Customer.  # noqa: E501
        :type firstname: str
        :param lastname: The lastname of this Customer.  # noqa: E501
        :type lastname: str
        :param address: The address of this Customer.  # noqa: E501
        :type address: str
        :param phone: The phone of this Customer.  # noqa: E501
        :type phone: str
        :param begin_date: The begin_date of this Customer.  # noqa: E501
        :type begin_date: date
        """
        self.swagger_types = {
            'id': int,
            'firstname': str,
            'lastname': str,
            'address': str,
            'phone': str,
            'begin_date': date
        }

        self.attribute_map = {
            'id': 'id',
            'firstname': 'firstname',
            'lastname': 'lastname',
            'address': 'address',
            'phone': 'phone',
            'begin_date': 'begin_date'
        }
        self._id = id
        self._firstname = firstname
        self._lastname = lastname
        self._address = address
        self._phone = phone
        self._begin_date = begin_date

    @classmethod
    def from_dict(cls, dikt) -> 'Customer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Customer of this Customer.  # noqa: E501
        :rtype: Customer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Customer.


        :return: The id of this Customer.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Customer.


        :param id: The id of this Customer.
        :type id: int
        """

        self._id = id

    @property
    def firstname(self) -> str:
        """Gets the firstname of this Customer.


        :return: The firstname of this Customer.
        :rtype: str
        """
        return self._firstname

    @firstname.setter
    def firstname(self, firstname: str):
        """Sets the firstname of this Customer.


        :param firstname: The firstname of this Customer.
        :type firstname: str
        """

        self._firstname = firstname

    @property
    def lastname(self) -> str:
        """Gets the lastname of this Customer.


        :return: The lastname of this Customer.
        :rtype: str
        """
        return self._lastname

    @lastname.setter
    def lastname(self, lastname: str):
        """Sets the lastname of this Customer.


        :param lastname: The lastname of this Customer.
        :type lastname: str
        """

        self._lastname = lastname

    @property
    def address(self) -> str:
        """Gets the address of this Customer.


        :return: The address of this Customer.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this Customer.


        :param address: The address of this Customer.
        :type address: str
        """

        self._address = address

    @property
    def phone(self) -> str:
        """Gets the phone of this Customer.


        :return: The phone of this Customer.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """Sets the phone of this Customer.


        :param phone: The phone of this Customer.
        :type phone: str
        """

        self._phone = phone

    @property
    def begin_date(self) -> date:
        """Gets the begin_date of this Customer.


        :return: The begin_date of this Customer.
        :rtype: date
        """
        return self._begin_date

    @begin_date.setter
    def begin_date(self, begin_date: date):
        """Sets the begin_date of this Customer.


        :param begin_date: The begin_date of this Customer.
        :type begin_date: date
        """

        self._begin_date = begin_date
